### ISSUE TITLE
[BUG] Hiding the RocketMan button does not persist through a game restart.

### ISSUE THREAD

**Issue by andrewjrhill** [kbatbouta/RimWorld-RocketMan#16]
**Describe the bug**

The RocketMan button remains in the bottom menu bar after restarting the application; despite switching it off in the mod settings. 

**To Reproduce**
1. Go to Mod settings for RocketMan
2. Click Show RocketMan button/icon to hide the button from the main RimWorld navigation bar.
3. Restart the game.
5. A button in an "empty state" (not clickable, no icon) will be present where the RocketMan button usually is.
6. Go back into the Mod settings for RocketMan.
7. Click Show RocketMan button/icon to resolve.

**Expected behavior**
The "hiding" of the button should ideally persist through a game restart.

**Screenshots**

An exmple of the "empty state" button in the lower menu bar after restarting the game:

![Screenshot 2021-06-05 at 12 55 43](https://user-images.githubusercontent.com/3358672/120889652-74fc7800-c5fe-11eb-8c59-52304f3d32e7.png)

A demo of what users need to do each time the game is restarted to keep the button from re-appearing:

https://user-images.githubusercontent.com/3358672/120889677-95c4cd80-c5fe-11eb-832a-72673f64677e.mov

**Environment:**
 - RimWorld Version 1.2.x
 - MacOS

**Comment by kbatbouta** [comment]
Will fix soon.

**Comment by kbatbouta** [comment]
Fixed in the latest commits. Thanks for the report!

**Comment by andrewjrhill** [comment]
@kbatbouta - thanks! Fantastic mod by the way! Really appreciate what you've put together here!
