### ISSUE TITLE
[BUG] IndexOutOfRangeException in AlertsReadout_AlertsReadoutUpdate_Patch.ShouldUpdate

### ISSUE THREAD

**Issue by acctforrandomstuff** [kbatbouta/RimWorld-RocketMan#20]
> Exception in UIRootUpdate: System.IndexOutOfRangeException: Index was outside the bounds of the array.
> at Proton.AlertsReadout_AlertsReadoutUpdate_Patch.ShouldUpdate (System.Int32 index) [0x00009] in <d8cdf016301c4cfdbe5ef437eb06a04f>:0
> at (wrapper dynamic-method) RimWorld.AlertsReadout.RimWorld.AlertsReadout.AlertsReadoutUpdate_Patch0(RimWorld.AlertsReadout)
> at RimWorld.UIRoot_Play.UIRootUpdate () [0x00020] in <0feb66f0236b4f2faa0d13d3d46f45b1>:0 

It seems [Lines 217-221](https://github.com/kbatbouta/RimWorld-RocketMan/blob/6ec8b3530ba244ef067c1258d2b15ee55ea69115/Source/Proton/Core/Patches/AlertsReadout_Patch.cs#L217-L221) of `Proton.AlertsReadout_AlertsReadoutUpdate_Patch` (Proton/Core/Patches/AlertsReadout_Patch.cs) is exceeding the index of the `for` loop at [Line 169](https://github.com/kbatbouta/RimWorld-RocketMan/blob/6ec8b3530ba244ef067c1258d2b15ee55ea69115/Source/Proton/Core/Patches/AlertsReadout_Patch.cs#L169).

**Comment by kbatbouta** [comment]
Please provide the full report you full bug report.  Lines 217-221 of `Proton.AlertsReadout_AlertsReadoutUpdate_Patch` has nothing to do with it. These are Harmony patches and have a different stack trace format.

Please provide all the information as mentioned in the issues format.

**Comment by acctforrandomstuff** [comment]
I'm sorry if this is not an issue for your project. I just searched for words from the exception and found this repo. I briefly looked over the code I saw the code below, which looks to me like it would produce the Index Out of Range exception.
```cs
for (int i = 0; i < codes.Length; i++)
{
    //...
        if (codes[i + 1].labels == null)
        {
            codes[i + 1].labels = new List<Label>();
        }
        codes[i + 1].labels.Add(l1);
    //...
}
```

Rimworld v1.2.3005
Rocketman v0.6.3.2191
HugsLib log: https://gist.github.com/HugsLibRecordKeeper/6292002801f6f7fcaaaa0a8706b85a87

> Exception in UIRootUpdate: System.IndexOutOfRangeException: Index was outside the bounds of the array.  at Proton.AlertsReadout_AlertsReadoutUpdate_Patch.ShouldUpdate (System.Int32 index) [0x00009] in &lt;3d73fa4a5d264fae8483d91ee0f432a6&gt;:0   at (wrapper dynamic-method) RimWorld.AlertsReadout.RimWorld.AlertsReadout.AlertsReadoutUpdate_Patch0(RimWorld.AlertsReadout)  at (wrapper dynamic-method) RimWorld.UIRoot_Play.RimWorld.UIRoot_Play.UIRootUpdate_Patch1(RimWorld.UIRoot_Play)(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by kbatbouta** [comment]
This code is patching code not a code that run every tick.

**Comment by acctforrandomstuff** [comment]
I apologize for taking up your time with this then. Can you tell from the log which mod(s) might be causing this exception?

**Comment by kbatbouta** [comment]
It's fixed. I added more checks for this bug.

Thanks for the report!
