### ISSUE TITLE
Hospitality doesn't like Rocketman

### ISSUE THREAD

**Issue by docssy** [kbatbouta/RimWorld-RocketMan#35]
- Operating system: Win10
- Current behavior: Hospitality is overflowing the log with errors
- Excepted behavior: Stability
- General comment: 
- Logs
[RocketMan.zip](https://github.com/kbatbouta/RimWorld-RocketMan/files/7297373/RocketMan.zip)
[Player.log](https://github.com/kbatbouta/RimWorld-RocketMan/files/7297375/Player.log)

**Comment by brucethemoose** [comment]
You got some XML errors at startup, looks like some of them may be related to Misc Robots++? I have no conflict between Hospitality and Rocketman in my game.

But if you want to be sure, you can try disabling Rocketman in the mod's settings, and see if the pawn ticking errors still pop up.

**Comment by docssy** [comment]
No misc robots on this run

**Comment by alubedo** [comment]
May be easier to see the patches from a hugs log as well since it would show mod list in a easy readable way

**Comment by brucethemoose** [comment]
@docssy Ah. I saw some references to stuff like `BOT_Pacifist` and thought I remembered it from that mod.

Nevertheless, as alubedo said a hugslib log would be more helpful, and you should still try to address the red at startup.

**Comment by docssy** [comment]
[hugs.txt](https://github.com/kbatbouta/RimWorld-RocketMan/files/7298127/hugs.txt)

**Comment by docssy** [comment]
BOT_* I think is from one of the many trait mods.

**Comment by kbatbouta** [comment]
Your game is barely functional and is throwing every type of error possible during startup. Please try to reproduce with a smaller functional modlist.
