### ISSUE TITLE
Power consumption instability cause freezes [RW 1.3.3159, RM 1.3-hugslib-removal 71afb0f]

### ISSUE THREAD

**Issue by MekBoss** [kbatbouta/RimWorld-RocketMan#36]
**Describe the bug**
If lots of power consumer are connected to single electrical grid AND electrical production of that grid didnt satisfies consumption game starts to freezes for second or two every five or so seconds (when building decides should it turn on or off based on the amount of excess energy in the grid).

**To Reproduce**
1. Build lots of power production buildings, separated in two different groups (for example 20 solar panels, one group have 5 another 15).
2. At the group that have 5 panels build one battery.
3. Build wire that connects this two groups together.
4. From the group that have 5 solar panels build another long wire around of which build lots of basic turrets (110 should be enough).
5. Break the wire that connects groups of 5 panels with 15 panels.
6. After battery runs out of charge and turrets starts randomly activates/deactivates (oh, grid dont have enough power -> turns off -> oh, battery have some power in it -> turns on  -> goto 1) you should experience periodical freezes.

**Expected behavior**
Game shouldnt freeze. Disabling Rocketman from functioning in its menu confirms it, since it prevent freezes from happening, even if power problem is still didnt solved.

**Logs**
- Hugslib: Please upload your Hugslib report by clicking `CTRL+F12` then copying the report link here.
- Player.log: Upload your if you can.

**Screenshots**

**Environment (please complete the following information):**
 - RimWorld 1.3.3159
 - RocketMan, branch 1.3-hugslib-removal, commit 71afb0f
 - Windows 10 64 bits

**Additional context**

**Comment by alubedo** [comment]
Hmmm can't say I've ever heard of that even when used with insanely large modlist with more power buildings and consumers than even 150 
Wonder if it's triggered by something recent will need to check 
Side note the log would mention any errors if have it

**Comment by MekBoss** [comment]
Dont know is that something from recent commits or no, since I installed rocketman just half a hour before posting an issue.
And thats also the reason I figured out that it was it. Thats the only mod that I have added to the game.

**Comment by kbatbouta** [comment]
RocketMan doesn't modify the power grid. Please provide logs and your modlist incase this issue is still happening. Also, Are you using the prepatcher?
