### ISSUE TITLE
Request for documentation.

### ISSUE THREAD

**Issue by Epicguru** [kbatbouta/RimWorld-RocketMan#37]
Hello,
I would like to request some simple documentation be added to this project. I suspect that this mod is causing incompatibilities with some of my mods (by way caching). However it is hard for me to attempt to solve the issue because documentation does not exist on this github page...

The features section from the readme is incomplete, and the one on the Steam workshop only provides a very non-technical overview. It seems that there is a built-in compatibility patch feature, which is fantastic, but with 0 documentation on how to actually use it (i.e. what types of caches are there?), it's hard to use without finding it the source code.

And, although I think naming sub-projects after space shuttles is neat, it does also make it quite hard to tell what is what :)

I know that you mentioned that you were taking a break from active development of this for personal reasons, which is perfectly understandable (and I hope you're doing well), once you have the time and will I would greatly appreciate some more examples or explanations on the page. Thank you!

**Comment by kbatbouta** [comment]
Hi, Are you still having the issue and do you use Discord? 

Regarding the compatibility system. Yes, RocketMan will load Xml files; files that start with `rocket`, from other mods specificly files inside a folder called `Extra` in the root of said mod (so near the about folder). In this example https://github.com/kbatbouta/RimWorld-RocketMan/blob/development-1.4-unstable/1.4/Extras/RocketRules_Packages.xml RocketMan will ignore any def loaded by any of the listed mods. `IgnoreMe` need to have one of these attributes `defname` or `packageId`. You can either ask RocketMan to ignore all defs in a mod (using `packageId`) or specify them one by one  (using `defname`). 

If you want to force RocketMan to flush cache for a certain Thing (Pawns included) You can call `RocketMan.Tools:Notify_Dirty(Thing)` using reflection. 

Sorry for the delay and I hope this help.
