### ISSUE TITLE
Errors during load (harmless?)

### ISSUE THREAD

**Issue by sgtsquiggs** [kbatbouta/RimWorld-RocketMan#41]
Recently added two new mods and now RocketMan is very noisy at startup. Doesn't seem to affect gameplay however.

Exported logs here: https://gist.github.com/d3ba74e39f0390277b2cfec90f8e70a5

**Comment by alubedo** [comment]
HUH
Io access
it cant access the relevant file for some reason

**Comment by kbatbouta** [comment]
What os are you using? and are you using any type of sandboxing?

**Comment by sgtsquiggs** [comment]
Win11, updated from Win10 a week ago. Errors started after I added new mods.

**Comment by sgtsquiggs** [comment]
I wiped rocketman's directory and it seems to have recovered. "Cache not found or got purged!" :)
